import {
  Project,
  Member,
  NewsItem,
  Announcement,
  ContactInfo,
  BoardMember,
} from "./types";

// Mock projeler
export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Özel Ağaçlandırma Projesi",
    slug: "ozel-agaclandirma",
    description:
      "Bölgemizde sürdürülebilir orman yönetimi ve çevre koruma amacıyla başlatılan kapsamlı ağaçlandırma projesi. Bu proje ile hem çevresel hem de ekonomik faydalar sağlanması hedeflenmektedir.",
    shortDescription:
      "Erozyonu önleyen, doğal kaynakları koruyarak, çevre dostu ağaçlandırma ve karbon emisyonunu azaltma çalışması.",
    category: "ozel-agaclandirma",
    images: [],
    status: "active",
    startDate: "2023-01-15",
    budget: 2500000,
    location: "Şallıuşağı Bölgesi",
    features: [
      "1000 hektar alanda ağaçlandırma",
      "Yerli türlerin korunması",
      "Su kaynaklarının korunması",
      "Biyolojik çeşitliliğin artırılması",
    ],
    benefits: [
      "Karbon emisyonunun azaltılması",
      "Erozyonun önlenmesi",
      "Yerel istihdam yaratılması",
      "Turizm potansiyelinin artırılması",
    ],
    createdAt: "2023-01-01",
    updatedAt: "2024-01-15",
    hierarchy: "main",
    children: [],
  },
  {
    id: "100",
    title: "Hayvansal Üretim Projeleri",
    slug: "hayvansal-uretim",
    description:
      "Büyükbaş süt, büyükbaş besi ve küçükbaş üretim altyapılarının geliştirilmesi ve verimliliğin artırılması.",
    shortDescription:
      "Süt, besi ve küçükbaş üretiminde modern altyapı ve sürdürülebilir hayvancılık modeli.",
    category: "hayvansal-uretim",
    images: [],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [],
    benefits: [],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["2", "7", "8"],
  },
  {
    id: "101",
    title: "Bitkisel Üretim Projeleri",
    slug: "bitkisel-uretim",
    description:
      "Seracılık ve meyve bahçesi ile yıl boyu üretim ve modern sulama altyapıları.",
    shortDescription:
      "Seracılık ve meyve bahçeleriyle yıl boyu üretim, verimlilik ve tarımsal kalkınma",
    category: "bitkisel-uretim",
    images: [],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [],
    benefits: [],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["3", "9"],
  },
  {
    id: "102",
    title: "Tarımsal Sanayi Projeleri",
    slug: "tarimsal-sanayi",
    description:
      "Süt toplama ve soğutma, zeytinyağı üretimi ve fıstık işleme-paketleme tesisleri.",
    shortDescription:
      "Süt, zeytinyağı ve fıstık işleme tesisleriyle üretime değer katan sanayi projeleri.",
    category: "tarimsal-sanayi",
    images: [],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [],
    benefits: [],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["4", "10", "11"],
  },
  {
    id: "103",
    title: "El Sanatları Halı-Kilim Üretim Projeleri",
    slug: "el-sanatlari-hali-kilim",
    description:
      "Geleneksel dokuma, eğitim ve kooperatif markasıyla satış kanallarının geliştirilmesi.",
    shortDescription:
      "Geleneksel el sanatlarını modern üretimle buluşturan kültürel ve ekonomik girişim.",
    category: "el-sanatlari-hali-kilim",
    images: [],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [],
    benefits: [],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["5"],
  },
  {
    id: "2",
    title: "Büyükbaş Süt Üretim Projesi",
    slug: "buyukbas-sut",
    description:
      "Modern süt üretim teknikleri kullanarak kaliteli süt üretimi ve işlenmesi projesi. Kooperatif üyelerinin süt üretim kapasitelerini artırmayı hedeflemektedir.",
    shortDescription: "Hijyenik sağım ve soğuk zincirle kaliteli süt üretimi",
    category: "hayvansal-uretim",
    subcategory: "Büyükbaş Süt",
    images: [],
    status: "active",
    startDate: "2023-03-01",
    budget: 1800000,
    location: "Şallıuşağı Süt Üretim Merkezi",
    features: [
      "Modern süt sağım sistemi",
      "Soğutma ve depolama tesisleri",
      "Kalite kontrol laboratuvarı",
      "Eğitim ve danışmanlık hizmetleri",
    ],
    benefits: [
      "Süt kalitesinin artırılması",
      "Üretici gelirlerinin yükseltilmesi",
      "Pazar erişiminin kolaylaştırılması",
      "Teknoloji transferi",
    ],
    createdAt: "2023-02-15",
    updatedAt: "2024-01-10",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "7",
    title: "Büyükbaş Besi Projesi",
    slug: "buyukbas-besi",
    description:
      "Kooperatif üyeleri için modern besicilik altyapısı ile verimli ve sürdürülebilir büyükbaş besi üretimi.",
    shortDescription: "Modern altyapıyla verimli ve sürdürülebilir besicilik",
    category: "hayvansal-uretim",
    subcategory: "Büyükbaş Besi",
    images: [],
    status: "planning",
    startDate: "2024-05-01",
    budget: 1500000,
    location: "Şallıuşağı Hayvancılık Alanı",
    features: [
      "Kapalı ve açık besi alanları",
      "Otomasyonlu yemleme",
      "Sağlık ve izleme sistemi",
    ],
    benefits: [
      "Et veriminde artış",
      "Üretim maliyetlerinde azalma",
      "Pazar erişiminde kolaylık",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-02-10",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "8",
    title: "Küçükbaş Üretim Projesi",
    slug: "kucukbas",
    description:
      "Küçükbaş hayvancılık kapasitesini artırmak amacıyla meraya dayalı ve yarı entegre üretim modeli.",
    shortDescription: "Meraya dayalı, ölçeklenebilir küçükbaş üretim modeli",
    category: "hayvansal-uretim",
    subcategory: "Küçükbaş",
    images: [],
    status: "active",
    startDate: "2023-07-01",
    budget: 900000,
    location: "Şallıuşağı Yaylaları",
    features: [
      "Sürü yönetim sistemi",
      "Aşılama ve sağlık planı",
      "Yem bitkisi üretimi desteği",
    ],
    benefits: [
      "Süt ve et üretiminde artış",
      "Kırsal istihdama katkı",
      "Girdi maliyetlerinde verimlilik",
    ],
    createdAt: "2023-06-15",
    updatedAt: "2024-01-22",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "3",
    title: "Seracılık Projesi",
    slug: "seracilik",
    description:
      "Yıl boyunca sebze ve meyve üretimi için modern sera tesisleri kurulumu. İklim kontrollü üretim ile verimliliği artırma projesi.",
    shortDescription: "İklim kontrollü sera tesisleriyle yıl boyu yüksek verim",
    category: "bitkisel-uretim",
    subcategory: "Seracılık",
    images: [],
    status: "planning",
    startDate: "2024-06-01",
    budget: 3200000,
    location: "Şallıuşağı Tarım Alanları",
    features: [
      "İklim kontrollü sera sistemleri",
      "Hidroponik üretim teknikleri",
      "Otomatik sulama sistemi",
      "Enerji verimli aydınlatma",
    ],
    benefits: [
      "Yıl boyu üretim imkanı",
      "Su tasarrufu",
      "Yüksek verimlilik",
      "Organik üretim potansiyeli",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-20",
    hierarchy: "sub",
    parentId: "101",
  },
  {
    id: "9",
    title: "Meyve Bahçesi Projesi",
    slug: "meyve-bahcesi",
    description:
      "İklime uygun türlerle modern meyve bahçeleri kurulumu ve damla sulama altyapısının yaygınlaştırılması.",
    shortDescription:
      "Damla sulama ve doğru çeşit seçimiyle katma değerli meyvecilik",
    category: "bitkisel-uretim",
    subcategory: "Meyve Bahçesi",
    images: [],
    status: "planning",
    startDate: "2024-08-01",
    budget: 2100000,
    location: "Şallıuşağı Tarım Havzası",
    features: [
      "Damla sulama sistemi",
      "Toprak analizine dayalı gübreleme",
      "Fidan destek programı",
    ],
    benefits: ["Yüksek verim", "Su tasarrufu", "Uzun vadeli gelir artışı"],
    createdAt: "2024-03-01",
    updatedAt: "2024-03-10",
    hierarchy: "sub",
    parentId: "101",
  },
  {
    id: "4",
    title: "Zeytinyağı Üretim Tesisi",
    slug: "zeytinyagi-uretim",
    description:
      "Bölgedeki zeytin üreticileri için modern zeytinyağı üretim ve işleme tesisi. Soğuk sıkım teknikleri ile kaliteli zeytinyağı üretimi.",
    shortDescription:
      "Soğuk sıkım teknolojisiyle yüksek kaliteli zeytinyağı üretimi",
    category: "tarimsal-sanayi",
    subcategory: "Zeytinyağı Üretim Tesisi",
    images: [],
    status: "active",
    startDate: "2023-09-01",
    budget: 4500000,
    location: "Şallıuşağı Sanayi Bölgesi",
    features: [
      "Soğuk sıkım teknolojisi",
      "Kalite kontrol laboratuvarı",
      "Depolama ve ambalajlama",
      "Atık yönetim sistemi",
    ],
    benefits: [
      "Yüksek kaliteli zeytinyağı üretimi",
      "Üretici gelirlerinin artırılması",
      "Marka değeri yaratılması",
      "İhracat potansiyeli",
    ],
    createdAt: "2023-08-15",
    updatedAt: "2024-01-05",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "10",
    title: "Süt Toplama ve Soğutma Merkezi",
    slug: "sut-toplama-ve-sogutma-merkezi",
    description:
      "Bölgede üretilen sütün kalite kaybını önlemek için toplama, soğutma ve sevk altyapısı kurulumu.",
    shortDescription: "Toplamadan sevke kesintisiz soğuk zincir altyapısı",
    category: "tarimsal-sanayi",
    subcategory: "Süt Toplama ve Soğutma Merkezi",
    images: [],
    status: "active",
    startDate: "2023-10-01",
    budget: 1100000,
    location: "Şallıuşağı Süt Merkezi",
    features: [
      "Soğutma tankları",
      "Hijyenik toplama hattı",
      "Kalite test laboratuvarı",
    ],
    benefits: [
      "Süt kalitesinde iyileşme",
      "Fire kayıplarında azalma",
      "Üretici gelirlerinde artış",
    ],
    createdAt: "2023-09-10",
    updatedAt: "2024-01-18",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "11",
    title: "Fıstık Çıtlatma ve Paketleme Tesisi",
    slug: "fistik-citlatma-ve-paketleme-tesisi",
    description:
      "Bölgedeki fıstık üretiminin katma değerini artırmak için çıtlatma, ayıklama ve paketleme tesisi.",
    shortDescription:
      "Çıtlatmadan paketlemeye izlenebilir, katma değerli üretim",
    category: "tarimsal-sanayi",
    subcategory: "Fıstık Çıtlatma ve Paketleme Tesisi",
    images: [],
    status: "planning",
    startDate: "2024-11-01",
    budget: 2300000,
    location: "Şallıuşağı Sanayi Bölgesi",
    features: [
      "Çıtlatma ve eleme hattı",
      "Kalibrasyon ve kalite kontrol",
      "Vakum paketleme",
    ],
    benefits: [
      "Katma değerli üretim",
      "Marka ve ihracat potansiyeli",
      "Yeni istihdam olanakları",
    ],
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "5",
    title: "El Sanatları Üretim Merkezi",
    slug: "el-sanatlari-uretim",
    description:
      "Geleneksel el sanatlarımızı koruyarak modern üretim teknikleri ile birleştiren üretim merkezi. Halı, kilim ve diğer el sanatları üretimi.",
    shortDescription: "Geleneksel dokumayı modern üretimle buluşturan atölye",
    category: "el-sanatlari-hali-kilim",
    subcategory: "El Sanatları Üretim Merkezi",
    images: [],
    status: "active",
    startDate: "2023-11-01",
    budget: 1200000,
    location: "Şallıuşağı Kültür Merkezi",
    features: [
      "Geleneksel dokuma tezgahları",
      "Modern tasarım atölyesi",
      "Kalite kontrol birimi",
      "Eğitim ve kurs merkezi",
    ],
    benefits: [
      "Kültürel mirasın korunması",
      "Kadın istihdamının artırılması",
      "Turizm değeri yaratılması",
      "Gelir çeşitlendirmesi",
    ],
    createdAt: "2023-10-15",
    updatedAt: "2024-01-12",
    hierarchy: "sub",
    parentId: "103",
  },
  {
    id: "6",
    title: "Eğitim ve Spor Merkezi",
    slug: "egitim-spor-merkezi",
    description:
      "Bölge halkı için modern eğitim ve spor tesisleri. Çocuklar ve gençler için eğitim programları, yetişkinler için meslek edindirme kursları.",
    shortDescription:
      "Gençlere ve yetişkinlere yönelik eğitim, spor ve sosyal gelişim odaklı merkezler.",
    category: "egitim-spor-merkezi",
    images: [],
    status: "planning",
    startDate: "2024-09-01",
    budget: 2800000,
    location: "Şallıuşağı Merkez",
    features: [
      "Çok amaçlı spor salonu",
      "Kütüphane ve bilgisayar laboratuvarı",
      "Konferans ve toplantı salonları",
      "Açık spor alanları",
    ],
    benefits: [
      "Eğitim kalitesinin artırılması",
      "Sosyal aktivitelerin çeşitlendirilmesi",
      "Gençlerin gelişimine katkı",
      "Toplumsal birliktelik",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-18",
    hierarchy: "main",
    children: [],
  },
];

// Mock üyeler
export const mockMembers: Member[] = [
  {
    id: "1",
    name: "İbrahim",
    surname: "Çavaş",
    fullName: "İbrahim Çavaş",
    position: "Üye",
    email: "ibrahim.cavas@salliusagicoop.com",
    phone: "+90 532 123 45 67",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2020-01-15",
    isActive: true,
    role: "member",
  },
  {
    id: "2",
    name: "Kasım",
    surname: "Şapkur",
    fullName: "Kasım Şapkur",
    position: "Üye",
    email: "kasim.sapkur@salliusagicoop.com",
    phone: "+90 533 234 56 78",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2020-02-01",
    isActive: true,
    role: "member",
  },
  {
    id: "3",
    name: "Elmas",
    surname: "Çavaş",
    fullName: "Elmas Çavaş",
    position: "Üye",
    email: "elmas.cavas@salliusagicoop.com",
    phone: "+90 534 345 67 89",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2020-03-15",
    isActive: true,
    role: "member",
  },
  {
    id: "4",
    name: "Ali",
    surname: "Oğuz",
    fullName: "Ali Oğuz",
    position: "Üye",
    email: "ali.oguz@salliusagicoop.com",
    phone: "+90 535 456 78 90",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2020-04-01",
    isActive: true,
    role: "member",
  },
  {
    id: "5",
    name: "Döndü",
    surname: "Alakça",
    fullName: "Döndü Alakça",
    position: "Üye",
    email: "dondü.alakca@salliusagicoop.com",
    phone: "+90 536 567 89 01",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2021-01-15",
    isActive: true,
    role: "member",
  },
  {
    id: "6",
    name: "Cansu",
    surname: "Kurt",
    fullName: "Cansu Kurt",
    position: "Üye",
    email: "cansu.kurt@salliusagicoop.com",
    phone: "+90 537 678 90 12",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2021-02-15",
    isActive: true,
    role: "member",
  },
  {
    id: "7",
    name: "Aziz",
    surname: "Oğuz",
    fullName: "Aziz Oğuz",
    position: "Üye",
    email: "aziz.oguz@salliusagicoop.com",
    phone: "+90 538 789 01 23",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2021-03-15",
    isActive: true,
    role: "member",
  },
  {
    id: "8",
    name: "Yüksel",
    surname: "Oğuz",
    fullName: "Yüksel Oğuz",
    position: "Üye",
    email: "yuksel.oguz@salliusagicoop.com",
    phone: "+90 539 890 12 34",
    avatar: "",
    bio: "Kooperatif üyesi",
    joinDate: "2021-04-15",
    isActive: true,
    role: "member",
  },
];

// Mock yönetim kurulu
export const mockBoardMembers: BoardMember[] = [
  {
    id: "1",
    name: "İbrahim",
    surname: "Çavuş",
    fullName: "İbrahim Çavuş",
    position: "Başkan",
    email: "ibrahim.cavus@salliusagicoop.com",
    phone: "+90 532 123 45 67",
    avatar: "",
    bio: "Yönetim Kurulu Başkanı",
    joinDate: "2020-01-15",
    isActive: true,
    role: "board",
    order: 1,
    responsibilities: [
      "Genel koordinasyon ve yönetim",
      "Stratejik planlama",
      "Dış ilişkiler ve işbirliği",
    ],
  },
  {
    id: "2",
    name: "Kasım",
    surname: "Şapkur",
    fullName: "Kasım Şapkur",
    position: "Başkan Yrd.",
    email: "kasim.sapkur@salliusagicoop.com",
    phone: "+90 533 234 56 78",
    avatar: "",
    bio: "Yönetim Kurulu Başkan Yardımcısı",
    joinDate: "2020-02-01",
    isActive: true,
    role: "board",
    order: 2,
    responsibilities: [
      "Başkan yardımcılığı",
      "Üye ilişkileri",
      "Eğitim ve geliştirme",
    ],
  },
  {
    id: "3",
    name: "Ali",
    surname: "Oğuz",
    fullName: "Ali Oğuz",
    position: "Muhasip Üye",
    email: "ali.oguz@salliusagicoop.com",
    phone: "+90 534 345 67 89",
    avatar: "",
    bio: "Yönetim Kurulu Muhasip Üyesi",
    joinDate: "2020-03-15",
    isActive: true,
    role: "board",
    order: 3,
    responsibilities: [
      "Mali işler ve bütçe yönetimi",
      "Muhasebe ve raporlama",
      "Finansal planlama",
    ],
  },
];

// Mock denetim kurulu
export const mockAuditMembers: BoardMember[] = [
  {
    id: "1",
    name: "Bekir",
    surname: "Erenoğlu",
    fullName: "Bekir Erenoğlu",
    position: "Denetim Kurulu Üyesi",
    email: "bekir.erenoglu@salliusagicoop.com",
    phone: "+90 535 456 78 90",
    avatar: "",
    bio: "Denetim Kurulu Üyesi",
    joinDate: "2020-04-01",
    isActive: true,
    role: "audit",
    order: 1,
    responsibilities: ["Mali denetim", "İç kontrol", "Uyum denetimi"],
  },
  {
    id: "2",
    name: "Tevfik",
    surname: "Tokgöz",
    fullName: "Tevfik Tokgöz",
    position: "Denetim Kurulu Üyesi",
    email: "tevfik.tokgoz@salliusagicoop.com",
    phone: "+90 536 567 89 01",
    avatar: "",
    bio: "Denetim Kurulu Üyesi",
    joinDate: "2020-05-01",
    isActive: true,
    role: "audit",
    order: 2,
    responsibilities: [
      "Operasyonel denetim",
      "Risk değerlendirmesi",
      "Raporlama",
    ],
  },
];

// Mock haberler
export const mockNews: NewsItem[] = [
  {
    id: "1",
    title: "Zeytinyağı Üretim Tesisimiz Faaliyete Geçti",
    slug: "zeytinyagi-uretim-tesisi-faaliyete-gecti",
    content:
      "Şallıuşağı Üretim ve Pazarlama Kooperatifi olarak büyük bir gururla duyuruyoruz ki, modern zeytinyağı üretim tesisimiz resmi olarak faaliyete geçmiştir. Bu tesis ile bölgemizdeki zeytin üreticilerine kaliteli işleme hizmeti sunacağız...",
    excerpt:
      "Modern zeytinyağı üretim tesisimiz faaliyete geçti. Bölgemizdeki zeytin üreticilerine kaliteli işleme hizmeti sunmaya başladık.",
    author: "Ahmet Yılmaz",
    publishedAt: "2024-01-15",
    updatedAt: "2024-01-15",
    featuredImage: "",
    images: [],
    tags: ["zeytinyağı", "üretim", "tesis", "açılış"],
    isPublished: true,
    isFeatured: true,
    views: 245,
  },
  {
    id: "2",
    title: "Ağaçlandırma Projesinde İlk Fidanlar Dikildi",
    slug: "agaclandirma-projesinde-ilk-fidanlar-dikildi",
    content:
      "Özel ağaçlandırma projemiz kapsamında ilk fidanlarımızı toprakla buluşturduk. 1000 hektarlık alanda başlayan bu proje ile hem çevresel hem de ekonomik faydalar sağlamayı hedefliyoruz...",
    excerpt:
      "Özel ağaçlandırma projemizde ilk fidanlar dikildi. 1000 hektarlık alanda sürdürülebilir orman yönetimi başladı.",
    author: "Fatma Demir",
    publishedAt: "2024-01-10",
    updatedAt: "2024-01-10",
    featuredImage: "",
    images: [],
    tags: ["ağaçlandırma", "çevre", "sürdürülebilirlik", "proje"],
    isPublished: true,
    isFeatured: false,
    views: 189,
  },
  {
    id: "3",
    title: "El Sanatları Merkezi Kursları Başlıyor",
    slug: "el-sanatlari-merkezi-kurslari-basliyor",
    content:
      "Geleneksel el sanatlarımızı yaşatmak ve yeni nesillere aktarmak amacıyla El Sanatları Üretim Merkezimizde kurslar başlıyor. Halı, kilim ve diğer el sanatları konularında eğitimler verilecek...",
    excerpt:
      "El Sanatları Üretim Merkezimizde geleneksel el sanatları kursları başlıyor. Halı, kilim ve diğer el sanatları eğitimleri verilecek.",
    author: "Ayşe Özkan",
    publishedAt: "2024-01-08",
    updatedAt: "2024-01-08",
    featuredImage: "",
    images: [],
    tags: ["el sanatları", "kurs", "eğitim", "kültür"],
    isPublished: true,
    isFeatured: false,
    views: 156,
  },
];

// Mock duyurular
export const mockAnnouncements: Announcement[] = [
  {
    id: "1",
    title: "2024 Yılı Genel Kurul Toplantısı",
    slug: "2024-yili-genel-kurul-toplantisi",
    content:
      "Şallıuşağı Üretim ve Pazarlama Kooperatifi 2024 yılı genel kurul toplantısı 15 Mart 2024 tarihinde saat 14:00'da kooperatif merkezimizde yapılacaktır. Tüm üyelerimizin katılımını bekliyoruz.",
    excerpt:
      "2024 yılı genel kurul toplantısı 15 Mart 2024 tarihinde yapılacak. Tüm üyelerimizin katılımını bekliyoruz.",
    author: "Ahmet Yılmaz",
    publishedAt: "2024-01-20",
    updatedAt: "2024-01-20",
    isImportant: true,
    isPublished: true,
  },
  {
    id: "2",
    title: "Yeni Üye Kayıtları Başladı",
    slug: "yeni-uye-kayitlari-basladi",
    content:
      "2024 yılı için yeni üye kayıtları başlamıştır. Kooperatifimize katılmak isteyen üreticilerimiz 31 Mart 2024 tarihine kadar başvurularını yapabilirler.",
    excerpt:
      "2024 yılı için yeni üye kayıtları başladı. Başvurular 31 Mart 2024 tarihine kadar yapılabilir.",
    author: "Mehmet Kaya",
    publishedAt: "2024-01-18",
    updatedAt: "2024-01-18",
    isImportant: false,
    isPublished: true,
  },
  {
    id: "3",
    title: "Süt Toplama Merkezi Hizmete Açıldı",
    slug: "sut-toplama-merkezi-hizmete-acildi",
    content:
      "Modern süt toplama ve soğutma merkezimiz hizmete açılmıştır. Süt üreticilerimiz günlük sütlerini merkezimize getirerek kaliteli işleme hizmeti alabilirler.",
    excerpt:
      "Süt toplama ve soğutma merkezimiz hizmete açıldı. Süt üreticilerimiz günlük sütlerini merkezimize getirebilir.",
    author: "Fatma Demir",
    publishedAt: "2024-01-12",
    updatedAt: "2024-01-12",
    isImportant: false,
    isPublished: true,
  },
];

// İletişim bilgileri
export const contactInfo: ContactInfo = {
  address: {
    street: "Kooperatif Caddesi No: 15",
    district: "Merkez",
    city: "Şallıuşağı",
    postalCode: "12345",
    country: "Türkiye",
  },
  coordinates: {
    lat: 37.487933058089425,
    lng: 37.29279553682494,
  },
  phone: {
    primary: "+90 312 123 45 67",
    secondary: "+90 312 123 45 68",
    fax: "+90 312 123 45 69",
  },
  email: {
    primary: "info@salliusagicoop.com",
    info: "bilgi@salliusagicoop.com",
    support: "destek@salliusagicoop.com",
  },
  socialMedia: {
    facebook: "https://facebook.com/salliusagicoop",
    twitter: "https://twitter.com/salliusagicoop",
    instagram: "https://instagram.com/salliusagicoop",
    linkedin: "https://linkedin.com/company/salliusagicoop",
  },
  workingHours: {
    weekdays: "08:00 - 17:00",
    saturday: "09:00 - 13:00",
    sunday: "Kapalı",
  },
};
