import { Project, NewsItem, Announcement, ContactInfo } from "./types";

// Mock projeler
export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Özel Ağaçlandırma Projesi",
    slug: "ozel-agaclandirma",
    description:
      "Bölgemizde sürdürülebilir orman yönetimi ve çevre koruma amacıyla başlatılan kapsamlı ağaçlandırma projesi. Bu proje ile hem çevresel hem de ekonomik faydalar sağlanması hedeflenmektedir.",
    shortDescription:
      "Erozyonu önleyen, doğal kaynakları koruyarak, çevre dostu ağaçlandırma ve karbon emisyonunu azaltma çalışması.",
    category: "ozel-agaclandirma",
    images: ["/images/projects/ozel-agaclandirma/agaclandirma.jpg"],
    status: "active",
    startDate: "2023-01-15",
    budget: 2500000,
    location: "Şallıuşağı Bölgesi",
    features: [
      "1000 hektar alanda ağaçlandırma",
      "Yerli türlerin korunması",
      "Su kaynaklarının korunması",
      "Biyolojik çeşitliliğin artırılması",
    ],
    benefits: [
      "Karbon emisyonunun azaltılması",
      "Erozyonun önlenmesi",
      "Yerel istihdam yaratılması",
      "Turizm potansiyelinin artırılması",
    ],
    createdAt: "2023-01-01",
    updatedAt: "2024-01-15",
    hierarchy: "main",
    children: [],
  },
  {
    id: "100",
    title: "Hayvansal Üretim Projeleri",
    slug: "hayvansal-uretim",
    description:
      "Büyükbaş süt, büyükbaş besi ve küçükbaş üretim altyapılarının geliştirilmesi ve verimliliğin artırılması.",
    shortDescription:
      "Süt, besi ve küçükbaş üretiminde modern altyapı ve sürdürülebilir hayvancılık modeli.",
    category: "hayvansal-uretim",
    images: ["/images/projects/hayvansal-uretim/hayvansaluretim.jpg"],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [
      "Veterinerlik hizmet ağı ve aşılama takvimi",
      "Yem tedariki ve rasyon planlama desteği",
      "Süt toplama–soğuk zincir ve canlı tartım altyapısı",
      "Eğitim ve verimlilik ölçüm programları",
    ],
    benefits: [
      "Verim artışı ve birim maliyetlerde azalma",
      "Standardize kalite ve izlenebilirlik",
      "Kooperatif pazarlık gücü ve ortak satış",
      "Üretici gelirlerinde sürdürülebilir artış",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["2", "7", "8"],
  },
  {
    id: "101",
    title: "Bitkisel Üretim Projeleri",
    slug: "bitkisel-uretim",
    description:
      "Seracılık ve meyve bahçesi ile yıl boyu üretim ve modern sulama altyapıları.",
    shortDescription:
      "Seracılık ve meyve bahçeleriyle yıl boyu üretim, verimlilik ve tarımsal kalkınma",
    category: "bitkisel-uretim",
    images: ["/images/projects/bitkisel-uretim/bitkiseluretim.jpg"],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [
      "Damla sulama ve fertigation altyapısı",
      "İklim kontrollü sera–açık alan planlaması",
      "Toprak/yaprak analizine dayalı gübreleme",
      "Entegre zararlı yönetimi (IPM)",
    ],
    benefits: [
      "Su ve gübre tasarrufu",
      "Hastalık ve zararlı kayıplarında azalma",
      "Yıl boyu arz sürekliliği",
      "Pazar fiyat dalgalanmalarına karşı dayanıklılık",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["3", "9"],
  },
  {
    id: "102",
    title: "Tarımsal Sanayi Projeleri",
    slug: "tarimsal-sanayi",
    description:
      "Süt toplama ve soğutma, zeytinyağı üretimi ve fıstık işleme-paketleme tesisleri.",
    shortDescription:
      "Süt, zeytinyağı ve fıstık işleme tesisleriyle üretime değer katan sanayi projeleri.",
    category: "tarimsal-sanayi",
    images: ["/images/projects/tarimsal-sanayi/tarimsalsanayi.jpg"],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [
      "Gıda güvenliği standartları (HACCP/ISO 22000) uyumu",
      "Soğuk zincir ve lojistik entegrasyonu",
      "Paketleme–etiketleme (GS1 barkod) altyapısı",
      "Kalite kontrol ve izlenebilirlik yazılımı",
    ],
    benefits: [
      "Katma değerli ürün portföyü",
      "Firelerin azalması ve proses verimliliği",
      "Yeni pazar ve ihracat olanakları",
      "Marka bilinirliği ve güven artışı",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["4", "10", "11"],
  },
  {
    id: "103",
    title: "El Sanatları Halı-Kilim Üretim Projeleri",
    slug: "el-sanatlari-hali-kilim",
    description:
      "Geleneksel dokuma, eğitim ve kooperatif markasıyla satış kanallarının geliştirilmesi.",
    shortDescription:
      "Geleneksel el sanatlarını modern üretimle buluşturan kültürel ve ekonomik girişim.",
    category: "el-sanatlari-hali-kilim",
    images: ["/images/projects/el-sanatlari-hali-kilim/halikilim.jpg"],
    status: "planning",
    startDate: "2024-01-01",
    budget: 0,
    location: "Şallıuşağı",
    features: [
      "Usta–çırak eğitim programı",
      "Doğal boya ve yerel yün tedarik ağı",
      "Desen arşivi ve tasarım atölyesi",
      "Coğrafi işaret/sertifikasyon süreçleri",
    ],
    benefits: [
      "Kültürel mirasın yaşatılması",
      "Kadın ve genç istihdamı",
      "Daha yüksek birim satış değeri",
      "Kooperatif markasıyla sürdürülebilir gelir",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    hierarchy: "main",
    children: ["5"],
  },
  {
    id: "2",
    title: "Büyükbaş Süt Üretim Projesi",
    slug: "buyukbas-sut",
    description:
      "Modern süt üretim teknikleri kullanarak kaliteli süt üretimi ve işlenmesi projesi. Kooperatif üyelerinin süt üretim kapasitelerini artırmayı hedeflemektedir.",
    shortDescription: "Hijyenik sağım ve soğuk zincirle kaliteli süt üretimi",
    category: "hayvansal-uretim",
    subcategory: "Büyükbaş Süt",
    images: ["/images/projects/buyukbas-sut/buyukbassut.jpg"],
    status: "active",
    startDate: "2023-03-01",
    budget: 1800000,
    location: "Şallıuşağı Süt Üretim Merkezi",
    features: [
      "Modern süt sağım sistemi",
      "Soğutma ve depolama tesisleri",
      "Kalite kontrol laboratuvarı",
      "Eğitim ve danışmanlık hizmetleri",
    ],
    benefits: [
      "Süt kalitesinin artırılması",
      "Üretici gelirlerinin yükseltilmesi",
      "Pazar erişiminin kolaylaştırılması",
      "Teknoloji transferi",
    ],
    createdAt: "2023-02-15",
    updatedAt: "2024-01-10",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "7",
    title: "Büyükbaş Besi Projesi",
    slug: "buyukbas-besi",
    description:
      "Kooperatif üyeleri için modern besicilik altyapısı ile verimli ve sürdürülebilir büyükbaş besi üretimi.",
    shortDescription: "Modern altyapıyla verimli ve sürdürülebilir besicilik",
    category: "hayvansal-uretim",
    subcategory: "Büyükbaş Besi",
    images: ["/images/projects/buyukbas-besi/buyukbasbesi.jpg"],
    status: "planning",
    startDate: "2024-05-01",
    budget: 1500000,
    location: "Şallıuşağı Hayvancılık Alanı",
    features: [
      "Kapalı ve açık besi alanları",
      "Otomasyonlu yemleme",
      "Sağlık ve izleme sistemi",
    ],
    benefits: [
      "Et veriminde artış",
      "Üretim maliyetlerinde azalma",
      "Pazar erişiminde kolaylık",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-02-10",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "8",
    title: "Küçükbaş Üretim Projesi",
    slug: "kucukbas",
    description:
      "Küçükbaş hayvancılık kapasitesini artırmak amacıyla meraya dayalı ve yarı entegre üretim modeli.",
    shortDescription: "Meraya dayalı, ölçeklenebilir küçükbaş üretim modeli",
    category: "hayvansal-uretim",
    subcategory: "Küçükbaş",
    images: ["/images/projects/kucukbas/kucukbas.jpg"],
    status: "active",
    startDate: "2023-07-01",
    budget: 900000,
    location: "Şallıuşağı Yaylaları",
    features: [
      "Sürü yönetim sistemi",
      "Aşılama ve sağlık planı",
      "Yem bitkisi üretimi desteği",
    ],
    benefits: [
      "Süt ve et üretiminde artış",
      "Kırsal istihdama katkı",
      "Girdi maliyetlerinde verimlilik",
    ],
    createdAt: "2023-06-15",
    updatedAt: "2024-01-22",
    hierarchy: "sub",
    parentId: "100",
  },
  {
    id: "3",
    title: "Seracılık Projesi",
    slug: "seracilik",
    description:
      "Yıl boyunca sebze ve meyve üretimi için modern sera tesisleri kurulumu. İklim kontrollü üretim ile verimliliği artırma projesi.",
    shortDescription: "İklim kontrollü sera tesisleriyle yıl boyu yüksek verim",
    category: "bitkisel-uretim",
    subcategory: "Seracılık",
    images: ["/images/projects/seracilik/seracilik.jpg"],
    status: "planning",
    startDate: "2024-06-01",
    budget: 3200000,
    location: "Şallıuşağı Tarım Alanları",
    features: [
      "İklim kontrollü sera sistemleri",
      "Hidroponik üretim teknikleri",
      "Otomatik sulama sistemi",
      "Enerji verimli aydınlatma",
    ],
    benefits: [
      "Yıl boyu üretim imkanı",
      "Su tasarrufu",
      "Yüksek verimlilik",
      "Organik üretim potansiyeli",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-20",
    hierarchy: "sub",
    parentId: "101",
  },
  {
    id: "9",
    title: "Meyve Bahçesi Projesi",
    slug: "meyve-bahcesi",
    description:
      "İklime uygun türlerle modern meyve bahçeleri kurulumu ve damla sulama altyapısının yaygınlaştırılması.",
    shortDescription:
      "Damla sulama ve doğru çeşit seçimiyle katma değerli meyvecilik",
    category: "bitkisel-uretim",
    subcategory: "Meyve Bahçesi",
    images: ["/images/projects/meyve-bahcesi/meyvebahcesi.jpg"],
    status: "planning",
    startDate: "2024-08-01",
    budget: 2100000,
    location: "Şallıuşağı Tarım Havzası",
    features: [
      "Damla sulama sistemi",
      "Toprak analizine dayalı gübreleme",
      "Fidan destek programı",
    ],
    benefits: ["Yüksek verim", "Su tasarrufu", "Uzun vadeli gelir artışı"],
    createdAt: "2024-03-01",
    updatedAt: "2024-03-10",
    hierarchy: "sub",
    parentId: "101",
  },
  {
    id: "4",
    title: "Zeytinyağı Üretim Tesisi",
    slug: "zeytinyagi-uretim",
    description:
      "Bölgedeki zeytin üreticileri için modern zeytinyağı üretim ve işleme tesisi. Soğuk sıkım teknikleri ile kaliteli zeytinyağı üretimi.",
    shortDescription:
      "Soğuk sıkım teknolojisiyle yüksek kaliteli zeytinyağı üretimi",
    category: "tarimsal-sanayi",
    subcategory: "Zeytinyağı Üretim Tesisi",
    images: ["/images/projects/zeytinyagi-uretim/zeytinuretim.jpg"],
    status: "active",
    startDate: "2023-09-01",
    budget: 4500000,
    location: "Şallıuşağı Sanayi Bölgesi",
    features: [
      "Soğuk sıkım teknolojisi",
      "Kalite kontrol laboratuvarı",
      "Depolama ve ambalajlama",
      "Atık yönetim sistemi",
    ],
    benefits: [
      "Yüksek kaliteli zeytinyağı üretimi",
      "Üretici gelirlerinin artırılması",
      "Marka değeri yaratılması",
      "İhracat potansiyeli",
    ],
    createdAt: "2023-08-15",
    updatedAt: "2024-01-05",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "10",
    title: "Süt Toplama ve Soğutma Merkezi",
    slug: "sut-toplama-ve-sogutma-merkezi",
    description:
      "Bölgede üretilen sütün kalite kaybını önlemek için toplama, soğutma ve sevk altyapısı kurulumu.",
    shortDescription: "Toplamadan sevke kesintisiz soğuk zincir altyapısı",
    category: "tarimsal-sanayi",
    subcategory: "Süt Toplama ve Soğutma Merkezi",
    images: [
      "/images/projects/sut-toplama-ve-sogutma-merkezi/suttoplamavesogutma.jpg",
    ],
    status: "active",
    startDate: "2023-10-01",
    budget: 1100000,
    location: "Şallıuşağı Süt Merkezi",
    features: [
      "Soğutma tankları",
      "Hijyenik toplama hattı",
      "Kalite test laboratuvarı",
    ],
    benefits: [
      "Süt kalitesinde iyileşme",
      "Fire kayıplarında azalma",
      "Üretici gelirlerinde artış",
    ],
    createdAt: "2023-09-10",
    updatedAt: "2024-01-18",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "11",
    title: "Fıstık Çıtlatma ve Paketleme Tesisi",
    slug: "fistik-citlatma-ve-paketleme-tesisi",
    description:
      "Bölgedeki fıstık üretiminin katma değerini artırmak için çıtlatma, ayıklama ve paketleme tesisi.",
    shortDescription:
      "Çıtlatmadan paketlemeye izlenebilir, katma değerli üretim",
    category: "tarimsal-sanayi",
    subcategory: "Fıstık Çıtlatma ve Paketleme Tesisi",
    images: [
      "/images/projects/fistik-citlatma-ve-paketleme-tesisi/fistikcitlatma.jpg",
    ],
    status: "planning",
    startDate: "2024-11-01",
    budget: 2300000,
    location: "Şallıuşağı Sanayi Bölgesi",
    features: [
      "Çıtlatma ve eleme hattı",
      "Kalibrasyon ve kalite kontrol",
      "Vakum paketleme",
    ],
    benefits: [
      "Katma değerli üretim",
      "Marka ve ihracat potansiyeli",
      "Yeni istihdam olanakları",
    ],
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    hierarchy: "sub",
    parentId: "102",
  },
  {
    id: "5",
    title: "El Sanatları Üretim Merkezi",
    slug: "el-sanatlari-uretim",
    description:
      "Geleneksel el sanatlarımızı koruyarak modern üretim teknikleri ile birleştiren üretim merkezi. Halı, kilim ve diğer el sanatları üretimi.",
    shortDescription: "Geleneksel dokumayı modern üretimle buluşturan atölye",
    category: "el-sanatlari-hali-kilim",
    subcategory: "El Sanatları Üretim Merkezi",
    images: ["/images/projects/el-sanatlari-uretim/elsanatlariuretim.jpg"],
    status: "active",
    startDate: "2023-11-01",
    budget: 1200000,
    location: "Şallıuşağı Kültür Merkezi",
    features: [
      "Geleneksel dokuma tezgahları",
      "Modern tasarım atölyesi",
      "Kalite kontrol birimi",
      "Eğitim ve kurs merkezi",
    ],
    benefits: [
      "Kültürel mirasın korunması",
      "Kadın istihdamının artırılması",
      "Turizm değeri yaratılması",
      "Gelir çeşitlendirmesi",
    ],
    createdAt: "2023-10-15",
    updatedAt: "2024-01-12",
    hierarchy: "sub",
    parentId: "103",
  },
  {
    id: "6",
    title: "Eğitim ve Spor Merkezi",
    slug: "egitim-spor-merkezi",
    description:
      "Bölge halkı için modern eğitim ve spor tesisleri. Çocuklar ve gençler için eğitim programları, yetişkinler için meslek edindirme kursları.",
    shortDescription:
      "Gençlere ve yetişkinlere yönelik eğitim, spor ve sosyal gelişim odaklı merkezler.",
    category: "egitim-spor-merkezi",
    images: ["/images/projects/egitim-spor-merkezi/egitimspormerkezi.jpg"],
    status: "planning",
    startDate: "2024-09-01",
    budget: 2800000,
    location: "Şallıuşağı Merkez",
    features: [
      "Çok amaçlı spor salonu",
      "Kütüphane ve bilgisayar laboratuvarı",
      "Konferans ve toplantı salonları",
      "Açık spor alanları",
    ],
    benefits: [
      "Eğitim kalitesinin artırılması",
      "Sosyal aktivitelerin çeşitlendirilmesi",
      "Gençlerin gelişimine katkı",
      "Toplumsal birliktelik",
    ],
    createdAt: "2024-01-01",
    updatedAt: "2024-01-18",
    hierarchy: "main",
    children: [],
  },
];

// Mock haberler
export const mockNews: NewsItem[] = [
  {
    id: "1",
    title: "Zeytinyağı Üretim Tesisimiz Faaliyete Geçti",
    slug: "zeytinyagi-uretim-tesisi-faaliyete-gecti",
    content:
      "Şallıuşağı Üretim ve Pazarlama Kooperatifi olarak büyük bir gururla duyuruyoruz ki, modern zeytinyağı üretim tesisimiz resmi olarak faaliyete geçmiştir. Bu tesis ile bölgemizdeki zeytin üreticilerine kaliteli işleme hizmeti sunacağız...",
    excerpt:
      "Modern zeytinyağı üretim tesisimiz faaliyete geçti. Bölgemizdeki zeytin üreticilerine kaliteli işleme hizmeti sunmaya başladık.",
    author: "Ahmet Yılmaz",
    publishedAt: "2024-01-15",
    updatedAt: "2024-01-15",
    featuredImage: "",
    images: [],
    tags: ["zeytinyağı", "üretim", "tesis", "açılış"],
    isPublished: true,
    isFeatured: true,
  },
  {
    id: "2",
    title: "Ağaçlandırma Projesinde İlk Fidanlar Dikildi",
    slug: "agaclandirma-projesinde-ilk-fidanlar-dikildi",
    content:
      "Özel ağaçlandırma projemiz kapsamında ilk fidanlarımızı toprakla buluşturduk. 1000 hektarlık alanda başlayan bu proje ile hem çevresel hem de ekonomik faydalar sağlamayı hedefliyoruz...",
    excerpt:
      "Özel ağaçlandırma projemizde ilk fidanlar dikildi. 1000 hektarlık alanda sürdürülebilir orman yönetimi başladı.",
    author: "Fatma Demir",
    publishedAt: "2024-01-10",
    updatedAt: "2024-01-10",
    featuredImage: "",
    images: [],
    tags: ["ağaçlandırma", "çevre", "sürdürülebilirlik", "proje"],
    isPublished: true,
    isFeatured: false,
  },
  {
    id: "3",
    title: "El Sanatları Merkezi Kursları Başlıyor",
    slug: "el-sanatlari-merkezi-kurslari-basliyor",
    content:
      "Geleneksel el sanatlarımızı yaşatmak ve yeni nesillere aktarmak amacıyla El Sanatları Üretim Merkezimizde kurslar başlıyor. Halı, kilim ve diğer el sanatları konularında eğitimler verilecek...",
    excerpt:
      "El Sanatları Üretim Merkezimizde geleneksel el sanatları kursları başlıyor. Halı, kilim ve diğer el sanatları eğitimleri verilecek.",
    author: "Ayşe Özkan",
    publishedAt: "2024-01-08",
    updatedAt: "2024-01-08",
    featuredImage: "",
    images: [],
    tags: ["el sanatları", "kurs", "eğitim", "kültür"],
    isPublished: true,
    isFeatured: false,
  },
];

// Mock duyurular
export const mockAnnouncements: Announcement[] = [
  {
    id: "1",
    title: "2024 Yılı Genel Kurul Toplantısı",
    content:
      "Şallıuşağı Üretim ve Pazarlama Kooperatifi 2024 yılı genel kurul toplantısı 15 Mart 2024 tarihinde saat 14:00'da kooperatif merkezimizde yapılacaktır. Tüm üyelerimizin katılımını bekliyoruz.\n\nToplantıda aşağıdaki konular görüşülecektir:\n• 2023 yılı faaliyet raporu\n• 2024 yılı bütçe planı\n• Yeni yönetim kurulu seçimi\n• Üye aidatları güncellemesi\n\nKatılım için önceden kayıt yaptırmanız gerekmektedir. Kayıt işlemleri için kooperatif merkezimize başvurabilir veya telefon ile iletişime geçebilirsiniz.",
    date: "2024-01-20",
    published: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    isImportant: false,
    author: "Ahmet Yılmaz",
  },
  {
    id: "2",
    title: "Yeni Üye Kayıtları Başladı",
    content:
      "2024 yılı için yeni üye kayıtları başlamıştır. Kooperatifimize katılmak isteyen üreticilerimiz 31 Mart 2024 tarihine kadar başvurularını yapabilirler.\n\nÜyelik için gerekli belgeler:\n• Kimlik fotokopisi\n• İkametgah belgesi\n• Tarım faaliyet belgesi\n• 2 adet fotoğraf\n\nÜyelik aidatı: 500 TL (tek seferlik)\nYıllık aidat: 200 TL\n\nBaşvuru formları kooperatif merkezimizden temin edilebilir. Detaylı bilgi için lütfen iletişime geçiniz.",
    date: "2024-01-18",
    published: true,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    isImportant: false,
    author: "Mehmet Kaya",
  },
  {
    id: "3",
    title: "Süt Toplama Merkezi Hizmete Açıldı",
    content:
      "Modern süt toplama ve soğutma merkezimiz hizmete açılmıştır. Süt üreticilerimiz günlük sütlerini merkezimize getirerek kaliteli işleme hizmeti alabilirler.\n\nMerkezimizin özellikleri:\n• Günlük 5000 litre süt işleme kapasitesi\n• Soğutma sistemi ile süt kalitesi korunması\n• Laboratuvar analiz hizmetleri\n• Uygun fiyatlarla süt alımı\n\nÇalışma saatleri:\n• Hafta içi: 06:00 - 18:00\n• Cumartesi: 06:00 - 14:00\n• Pazar: Kapalı\n\nSüt getiren üreticilerimiz için özel indirimler uygulanmaktadır.",
    date: "2024-01-12",
    published: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
    isImportant: false,
    author: "Fatma Demir",
  },
  {
    id: "4",
    title: "Tarımsal Eğitim Programları Başlıyor",
    content:
      "Kooperatifimiz bünyesinde düzenlenecek tarımsal eğitim programları 1 Şubat 2024 tarihinde başlayacaktır. Programlar ücretsiz olup tüm üyelerimiz katılabilir.\n\nEğitim konuları:\n• Modern tarım teknikleri\n• Organik tarım uygulamaları\n• Hayvancılık yönetimi\n• Pazarlama stratejileri\n• Kooperatifçilik ilkeleri\n\nEğitimler hafta sonları düzenlenecek olup, katılım sertifikası verilecektir. Kayıt için kooperatif merkezimize başvurabilirsiniz.",
    date: "2024-01-10",
    published: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    isImportant: false,
    author: "Zeynep Özkan",
  },
  {
    id: "5",
    title: "Ürün Satış Fiyatları Güncellendi",
    content:
      "2024 yılı ürün satış fiyatları güncellenmiştir. Yeni fiyat listesi aşağıda yer almaktadır:\n\nSüt Ürünleri:\n• Çiğ süt: 8,50 TL/litre\n• Yoğurt: 12 TL/kg\n• Peynir: 45 TL/kg\n\nSebze Ürünleri:\n• Domates: 15 TL/kg\n• Salatalık: 8 TL/kg\n• Biber: 20 TL/kg\n\nMeyve Ürünleri:\n• Elma: 12 TL/kg\n• Armut: 10 TL/kg\n• Şeftali: 18 TL/kg\n\nFiyatlar günlük olarak değişebilir. Güncel fiyatlar için kooperatif merkezimizi arayabilirsiniz.",
    date: "2024-01-08",
    published: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
    isImportant: true,
    author: "Ali Çelik",
  },
];

// İletişim bilgileri
export const contactInfo: ContactInfo = {
  address: {
    street: "Kooperatif Caddesi No: 15",
    district: "Merkez",
    city: "Şallıuşağı",
    postalCode: "12345",
    country: "Türkiye",
  },
  coordinates: {
    lat: 37.487933058089425,
    lng: 37.29279553682494,
  },
  phone: {
    primary: "+90 312 123 45 67",
    secondary: "+90 312 123 45 68",
    fax: "+90 312 123 45 69",
  },
  email: {
    primary: "info@salliusagikoop.com",
    info: "bilgi@salliusagikoop.com",
    support: "destek@salliusagikoop.com",
  },
  socialMedia: {
    facebook: "https://facebook.com/salliusagikoop",
    twitter: "https://twitter.com/salliusagikoop",
    instagram: "https://instagram.com/salliusagikoop",
    linkedin: "https://linkedin.com/company/salliusagikoop",
  },
  workingHours: {
    weekdays: "08:00 - 17:00",
    saturday: "09:00 - 13:00",
    sunday: "Kapalı",
  },
};
